### ISSUE TITLE
cosmid list raises IndentationError

### ISSUE THREAD

**Issue by alneberg** [robinandeer/cosmid#26]
Hi,
I ran

```
pip install cosmid
cosmid init
cosmid list
```

but this raises
    Available resources (key - description):

```
Traceback (most recent call last):
File "/Users/johannesalneberg/.virtualenvs/cosmid/bin/cosmid", line 217, in <module>
    main(args)
  File "/Users/johannesalneberg/.virtualenvs/cosmid/bin/cosmid", line 65, in main
   for item in hub.ls():
  File "/Users/johannesalneberg/.virtualenvs/cosmid/lib/python2.7/site-packages/cosmid/core.py", line 289, in ls
  module = self.get(modname, type_="module")
  File "/Users/johannesalneberg/.virtualenvs/cosmid/lib/python2.7/site-packages/cosmid/core.py", line 179, in get
   return importlib.import_module("cosmid.resources." + resource_id)
  File  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
__import__(name)
  File "/Users/johannesalneberg/.virtualenvs/cosmid/lib/python2.7/site-packages/cosmid/resources/decoy.py", line 17
    "phase2_reference_assembly_sequence"
    ^
IndentationError: unexpected indent
```

Cheers,
Johannes

**Comment by robinandeer** [comment]
That's what you get for trying to follow pep8 like a slave :)

Will fix tomorrow.

**Comment by robinandeer** [comment]
Bug is fixed and I will upload to cheeseshop when it's back online.
